#pragma once

// engine/assets/audio/audio_clip.h
//
// Runtime data types and table for the audio clip asset — the first CPU-resident
// asset family that is not backed by a GPU resource (audio lives entirely on the
// CPU and is consumed by the realtime mixer, not the renderer).
//
// ── Ownership model ───────────────────────────────────────────────────────────
//
// The AssetSystem stores a ResourceHandle in compiled node payloads. The actual
// AudioClipData lives in AudioClipTable, owned by EngineAssetLibrary.
// AudioClipTable::add() stores the data and returns the handle;
// AudioClipTable::get() resolves it back. This mirrors ScalarFieldTable.
//
// ── Separation of concerns ────────────────────────────────────────────────────
//
// AudioClipData                  — immutable, decoded interleaved-float32 PCM
// AudioClipTable                 — runtime owner of resolved clip data
// AudioClipWavCompileDesc        — metadata for WAV file-backed compile nodes
// ProceduralToneAudioClipCompileDesc — metadata for procedural tone compile nodes
//   (name is an identity input to the key factory, not a compile input, so it is
//    intentionally absent from the procedural compile descriptor)

#include <asset/types.h>

#include <cstdint>
#include <vector>

namespace wz::engine::assets {

    // ─── AudioClipSource ──────────────────────────────────────────────────────────
    //
    // Provenance of a decoded clip. Recorded for debugging/inspection only — it is
    // NOT part of the playback contract (a clip is always interleaved float32 once
    // decoded, regardless of where it came from).

    enum class AudioClipSource : uint8_t
    {
        Unknown,
        Wav,
        ProceduralTone,
    };


    // ─── AudioToneWaveform ────────────────────────────────────────────────────────
    //
    // Waveform generated by the procedural tone recipe. Used as an ordinal in the
    // key factory so different waveforms produce distinct AssetKeys even with
    // identical frequency/duration/amplitude.

    enum class AudioToneWaveform : uint8_t
    {
        Sine,
        Square,
        Saw,
        Triangle,
    };


    // ─── AudioClipData ────────────────────────────────────────────────────────────
    //
    // Immutable, CPU-side decoded PCM. Samples are interleaved float32 in [-1, 1],
    // frame-major: samples[frame * channels + channel]. This matches both the WAV
    // data layout and the interleaved-float output the audio device expects, and is
    // directly readable by the future interpolating-sampler voice (stride = channels).

    struct AudioClipData
    {
        uint32_t sample_rate = 0;   // frames per second
        uint32_t channels = 0;      // interleaved channel count
        uint64_t frame_count = 0;   // samples per channel

        AudioClipSource source = AudioClipSource::Unknown;

        std::vector<float> samples;  // interleaved, size == frame_count * channels

        uint64_t sample_count() const noexcept
        {
            return frame_count * static_cast<uint64_t>(channels);
        }

        double duration_seconds() const noexcept
        {
            return sample_rate > 0
                ? static_cast<double>(frame_count) / static_cast<double>(sample_rate)
                : 0.0;
        }

        bool valid() const noexcept
        {
            return sample_rate > 0
                && channels > 0
                && frame_count > 0
                && samples.size() == static_cast<size_t>(sample_count());
        }

        // Interleaved sample accessor. frame in [0, frame_count), ch in [0, channels).
        float at(uint64_t frame, uint32_t ch = 0) const
        {
            return samples[static_cast<size_t>(frame) * channels + ch];
        }
    };


    // ─── AudioClipWavCompileDesc ──────────────────────────────────────────────────
    //
    // Stored in AssetNode::meta for WAV file-backed compile nodes. The decoder reads
    // sample rate, channel count, and format directly from the WAV header, so V1 has
    // no authored parameters — the file dependency fully determines the output. The
    // struct exists so the compiler can distinguish a typed desc from a ParamBlock
    // and to leave room for future import knobs (resample target, normalize, etc.).

    struct AudioClipWavCompileDesc
    {
    };


    // ─── ProceduralToneAudioClipCompileDesc ───────────────────────────────────────
    //
    // Stored in AssetNode::meta for procedural tone compile nodes. The compiler
    // generates samples from these parameters alone — no file dependency.
    //
    // name is intentionally absent: it is an identity input to the key factory (so
    // differently-named tones with identical parameters are distinct assets), but
    // the compiler does not need it to generate samples.

    struct ProceduralToneAudioClipCompileDesc
    {
        uint32_t sample_rate = 48000;
        uint32_t channels = 1;

        AudioToneWaveform waveform = AudioToneWaveform::Sine;

        float frequency = 440.0f;        // hertz
        float duration_seconds = 1.0f;   // length of the generated clip
        float amplitude = 0.5f;          // peak amplitude in [0, 1]
    };


    // ─── AudioClipTable ───────────────────────────────────────────────────────────
    //
    // Runtime owner of resolved audio clip data. The AssetSystem stores only a
    // ResourceHandle; the actual AudioClipData lives in this table.
    //
    // V1: append-only. Free-list reuse / eviction (the "lifetime/eviction" the audio
    // track calls for) is deferred — clips are released wholesale by destroy().
    // Epoch starts at 1 — epoch 0 in a ResourceHandle always indicates invalid.

    class AudioClipTable
    {
    public:
        // Reserves slot 0 as the invalid sentinel so all real handles have id >= 1.
        AudioClipTable();

        // Store a resolved clip and return a handle to it.
        wz::asset::ResourceHandle add(AudioClipData clip);

        // Look up a clip by handle. Returns nullptr if the handle is stale or out of
        // range. Const — does not modify the table.
        const AudioClipData* get(wz::asset::ResourceHandle handle) const;

        // Mutable access for tests only. Not for use in production code paths.
        AudioClipData* get_mutable_for_tests(wz::asset::ResourceHandle handle);

        // Release all slots. Invalidates all outstanding handles.
        void destroy();

    private:
        struct Slot
        {
            uint32_t      epoch = 0;
            bool          occupied = false;
            AudioClipData clip;
        };

        std::vector<Slot> slots_;
    };

} // namespace wz::engine::assets
